### ISSUE TITLE
Buttons do not render on IOS devices

### ISSUE THREAD

**Issue by mew0717** [Sian-Lee-SA/honeycomb-menu#11]
The only thing that renders on the Iphone or Ipad (Both in the Home Assistant App or independent browsers) is the XYPad.
![UNADJUSTEDNONRAW_thumb_6](https://user-images.githubusercontent.com/1856673/116934445-fe511100-ac32-11eb-97a6-8d28139a4e29.jpg)

**Comment by mew0717** [comment]
I should note that the experience works fine in Chrome / Brave on OSX
<img width="1280" alt="Honeycomb MAC OSX" src="https://user-images.githubusercontent.com/1856673/116934884-859e8480-ac33-11eb-8478-f859e40be03d.png">

**Comment by Sian-Lee-SA** [comment]
That also happens on firefox from my recent experience and which is why I also noted in the readme that it was designed with Chrome in mind and as first priority. Android also uses chromes web views which also works on those devices... The culpit seems to be the CSSStyleSheets class which some browsers havent fully supported yet but is on my radar to fix.
