### ISSUE TITLE
The following call service with template is not supported

### ISSUE THREAD

**Issue by StefanoGiugliano** [Sian-Lee-SA/honeycomb-menu#53]
I'm trying to use this button to invoce the vacuum.send_command with a template for room id, but the service is not properly invoked... is says required key not provided data['command']. If I use the below service call with a normal button, it works properly.

                                          - icon: 'mdi:white-balance-sunny'
                                            tap_action:
                                              action: call-service
                                              service: honeycomb
                                              service_data:
                                                autoclose: true
                                                buttons:
                                                  - icon: 'mdi:toaster-oven'
                                                    tap_action:
                                                      action: call-service
                                                      service: vacuum.send_command
                                                      target:
                                                        entity_id: vacuum.aspirapolvere
                                                      data:
                                                        command: spot_area
                                                        params:
                                                          rooms: >-
                                                                       ${ parseInt(states['input_number.stanza_cucina'].state).toString() }
                                                          cleanings: 1

**Comment by Sian-Lee-SA** [comment]
This is not a honeycomb issue. Please refer to [custom button card](https://github.com/custom-cards/button-card)

**Comment by StefanoGiugliano** [comment]
What does it mean??? I'm not using custom button card....

This is the way you keep 0 issue open for your project? Randomly closing each issue you get?

**Comment by Sian-Lee-SA** [comment]
No I just expect people to read the documentation... Your whole code is not even a reflection of any examples or a reflection of what has been documented... What is `data` in there for? where did you get `target` from??? 

If you read the documentation, you would know that you are in fact using custom button card. you even have it installed otherwise menu items wouldn't appear. It's as simple as that.

https://github.com/Sian-Lee-SA/honeycomb-menu#button-options
The first line in that table clearly states the default card... (even under icon and color gives references to custom:button-card).

Issues have been addressed, that is why they're closed. 

Next time before trying to be critical it is advised to read the documenation. Again, this is not a Honeycomb issue as Honeycomb menu doesn't use any code that handles actions.

**Comment by Sian-Lee-SA** [comment]
There's even a link to a guide on the first line in the documentation that also explictly states about using Custom Button Card https://smarthomescene.com/guides/honeycomb-module-hex-popup-menu-for-home-assistant/.

**Comment by StefanoGiugliano** [comment]
As I said... if I invoke this on a normal button the below code, it works properly. 

                                                  action: call-service
                                                  service: vacuum.send_command
                                                  target:
                                                    entity_id: vacuum.aspirapolvere
                                                  data:
                                                    command: spot_area
                                                    params:
                                                      rooms: >-
                                                                   ${ parseInt(states['input_number.stanza_cucina'].state).toString() }
                                                      cleanings: 1

data and target are tags that vacuum.send_command expects when invoked... I understand now that your plugin is bugged and not able to manage this configuration. Thank you...

**Comment by Sian-Lee-SA** [comment]
I think you need to read up and understand how cards and integrations for Home Assistant works before posting issues outside your understanding. Your assumption that "data and target are tags that vacuum.send_command expects" is how I can tell you are not familiar at all about cutom cards in general.

Do me a favour... Do the exact code you did on custom button card and tell me how that goes... I'll wait. Your same code won't even work on  that card and it's more popular than the "normal button" card. 

So if it helps scratch your itch to call a plugin bugged when in fact you lack simple understanding of how cards works and couldn't be bothered reading a documenation then that's really your problem... you'll also noticed there isn't a single issue like this raised because everyone else understands how custom cards works and reads the documentation, so really i think the evidence shows that maybe it's you?
