### ISSUE TITLE
The menu shifts when you click away from the icon

### ISSUE THREAD

**Issue by Posstt** [Sian-Lee-SA/honeycomb-menu#60]
Hello, I assigned an image for this menu that needs to be clicked on for this menu to open, but I noticed that if I press my finger a little to the left to the right, the menu opens not in the center of the image, but where I clicked. And the currant is no longer in the center of the menu. Can this be fixed somehow?

**Comment by Posstt** [comment]
![12](https://github.com/Sian-Lee-SA/honeycomb-menu/assets/147872611/a00ca3cc-60a2-4dee-be76-0cb18d1c556f)
![23](https://github.com/Sian-Lee-SA/honeycomb-menu/assets/147872611/259c6ccb-2100-4dcc-b161-94485f76e073)

**Comment by Sian-Lee-SA** [comment]
The menu always opens to where you touch or click, this is the intended behaviour. Not something to be "fixed"

**Comment by Posstt** [comment]
Understood thanks. Your menu is simply amazing. If there was a customizable option to snap to the icon to center it, it would not be bad. Thank you for such a wonderful menu.

**Comment by Sian-Lee-SA** [comment]
Thanks, and to the customizable option, even though this module is in feature freeze it just wouldn't be possible to achieve as the action calling the menu gives no reference to the element/card calling it. So in simple terms, this menu has no way of targetting the element in the DOM, and even if it could, there's the other issue of what part of the card or DOM where as they're all different and every user would have their own desires to where it should show, The idea behind where it was last clicked or touched is to keep the user focused on the area where the action was called otherwise hands and mouse would be moving all over the place.
