### ISSUE TITLE
Update new sensor entity names

### ISSUE THREAD

**Issue by duceduc** [Sian-Lee-SA/honeycomb-menu#67]
I have since changed some of my sensor's name and want to update the floorplan layout. I thought we can just edit the xxx_optimized.svg file using notepad++ with the new entity id name. After a hard reset/reload, it does  not display the new sensor's state. I have updated my pc as well and do not wish to install the program. ( I forget what the name is. Inkscape is called?).  Am I correct to just edit the file and perhaps I need to wait a bit for the cache to kick in???

**Comment by Sian-Lee-SA** [comment]
you can edit the file and change the entity names through there (I tend to do this alot instead of opening inkscape). Any time you update or change the svg, update the file location in the floorplan yaml file and append an incrmented number eg. 

```yaml
config:
  image: /local/floorplan/areas_planner_optimized.svg?84
  stylesheet: /local/floorplan/area_svg.css?20
```
See the number after `?`, start with 1 then update that number each time you change either of those files. This makes the browser think it's a different file and won't use the chached version. Each time you change the yaml, use the update option in the lovelace view for changes to take affect. Also ensure your also changing the enitity names in you floorplan yaml aswell...

Will; close as this is **not** a Honeycomb menu issue and in future please use the appropriate channels relevant to your issue. Thanks.
